### PR TITLE
Change twitter links

### PR DESCRIPTION
**Pull request by c-martinez**
Changing the twitter link (only of the first paper to see if it works) for a plain link, with no twitter special effects -- could we check if this works for you?

### CODE REVIEW

**Comment by JeffCarver** [comment]
The plain link on the first paper works on my machine. If you want to fix the other papers, then I can merge the pull request. Thanks!

**Comment by c-martinez** [comment]
I fixed the rest of the papers, this should hopefully work now.

**Comment by JeffCarver** [comment]
﻿Thank you. I merged it. One question, I wonder if it would be better to change the twitter links for multiple authors so that it is just one box (i.e. “Tweet to @nasiresity, @jeffcarver32, @HaiAhNam1’) rather than three tweet buttons?

At this point is there anything else we need to do other than decide the permissions on the Google docs?

-- Jeff

Chair of UA Cyber Initiative
Professor and Graduate Program Director
Department of Computer Science
University of Alabama
205.348.9829 (v)

Calendar/GDrive requests: dr.jeff.carver@gmail.com<mailto:dr.jeff.carver@gmail.com>

**Comment by c-martinez** [comment]
We could, but it might look like one really long button. What do you think?

I don’t think there is much to do apart from decide on the google doc permissions, until we have the videos from all authors.

Best,
Carlos

**Pull request merged**
